version: '3.7'

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 127.0.0.1"

  consul-agent-socat:
    <<: *consul-agent
    build:
      context: .
      dockerfile: Dockerfile
    image: consul-connect:latest
    volumes:
      - ./config/socat:/consul/config

  consul-agent-web:
    <<: *consul-agent

  consul-agent-ui:
    <<: *consul-agent
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0 -ui"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"

  consul-server-1: &consul-server
    <<: *consul-agent
    volumes:
      - ./config/server:/consul/config
    command: "agent -server -retry-join consul-server-bootstrap -client 127.0.0.1"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-server
    command: "agent -server -bootstrap-expect 3 -client 127.0.0.1"

networks:
  consul-demo:
